name: Tag release

on:
  pull_request:
    types: [closed]

jobs:
  create_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR with title ${{ github.event.pull_request.title }} was merged
